// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolunteerRegistrationApp.Models;

namespace VolunteerRegistrationApp.Migrations
{
    [DbContext(typeof(VolunteersContext))]
    partial class VolunteersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("VolunteerRegistrationApp.Models.VolunteersRegistrationform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AadharCard")
                        .HasColumnType("longtext");

                    b.Property<string>("AltMobNo")
                        .HasColumnType("longtext");

                    b.Property<string>("AnySocialGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("Area")
                        .HasColumnType("longtext");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("DoB")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("GochriSeva")
                        .HasColumnType("longtext");

                    b.Property<string>("Landmark")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileNo")
                        .HasColumnType("longtext");

                    b.Property<string>("NameOfOrganization")
                        .HasColumnType("longtext");

                    b.Property<string>("NearestAirportNearest")
                        .HasColumnType("longtext");

                    b.Property<string>("NearestBusStation")
                        .HasColumnType("longtext");

                    b.Property<string>("NearestRailwayStation")
                        .HasColumnType("longtext");

                    b.Property<string>("Other")
                        .HasColumnType("longtext");

                    b.Property<int>("Pincode")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("longtext");

                    b.Property<string>("RouteCoordinator")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<string>("TownOrDistrict")
                        .HasColumnType("longtext");

                    b.Property<string>("ViharSeva")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VolunteersRegistrationform");
                });
#pragma warning restore 612, 618
        }
    }
}
